version: "3.9"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - postgres
    command: bash -c "yarn typeorm migration:run -d ./src/data-source && yarn dev"

  postgres:
    container_name: db_postgres
    image: postgres:latest
    ports:
      - 5431:5432
    env_file:
      - .env
